<a href="https://colab.research.google.com/github/chaehchaeh/DataAnalyzing/blob/main/221015%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%ED%8A%B9%EA%B0%95_%EB%84%98%ED%8C%8C%EC%9D%B4%EB%AC%B8%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#리스트의 복제와 어레이의 곱셈 비교
import numpy as np
x=[1,2,5,10]
print(x*3)
y=np.array(x)
print(y*3)

[1, 2, 5, 10, 1, 2, 5, 10, 1, 2, 5, 10]
[ 3  6 15 30]


In [2]:
#어레이를 리스트로 바꾸고 타입 확인하기
z=list(y)
print(z)
print(type(y))
print(type(z))

[1, 2, 5, 10]
<class 'numpy.ndarray'>
<class 'list'>


In [5]:
#어레이의 연산은 각 항목별로 수행된다
y1=np.array([1,2,3,4])
y2=np.array([10,10,100,100])
print(y1+y2)
print(y1-y2)
print(y1*y2)
print(y1/y2)

[ 11  12 103 104]
[ -9  -8 -97 -96]
[ 10  20 300 400]
[0.1  0.2  0.03 0.04]


In [8]:
#어레이에 단변수의 연산을 수행하기
y1=np.array([1,2,3,4])
a=1000

print(y1+a)
print(y1-a)
print(y1*a)
print(y1/a)

[1001 1002 1003 1004]
[-999 -998 -997 -996]
[1000 2000 3000 4000]
[0.001 0.002 0.003 0.004]


In [9]:
#리스트에 대한 +수행은 두 리스트를 합친다
y1=np.array([1,2,3,4])
y2=np.array([10,10,100,100])

list(y1)+list(y2)

[1, 2, 3, 4, 10, 10, 100, 100]

In [11]:
#일정한 간격의 수로 구성된 어레이를 얻는다.
print(np.arange(6))
print(np.arange(1,7))
print(np.arange(1,20,3))
print(np.arange(1,2,0.5))

[0 1 2 3 4 5]
[1 2 3 4 5 6]
[ 1  4  7 10 13 16 19]
[1.  1.5]


In [15]:
#임의의 도시정보 데이터프레임을 만드는 예
import pandas as pd
import numpy as np
x={'city':['서울','부산','대구','대전','광주'],
   'population':[990,350,250,154,150],
   'temp':[13,16,14,13,15],
   'cars':[300,120,80,90,70]}

df=pd.DataFrame(x)
df.set_index('city',inplace=True)
df

population  temp  cars
city                        
서울           990    13   300
부산           350    16   120
대구           250    14    80
대전           154    13    90
광주           150    15    70

In [16]:
#데이터 프레임을 어레이로 바꾸는 방법
z=df.values
print(z.shape)
z

(5, 3)


array([[990,  13, 300],
       [350,  16, 120],
       [250,  14,  80],
       [154,  13,  90],
       [150,  15,  70]])

In [17]:
#어레이는 바로 데이터 프레임으로 바꿀 수 있다

In [18]:
#데이터프레임을 만들면서 인덱스와 컬럼명을 지정

In [19]:
#어레이의 0~3 사이의 행을 얻기

In [20]:
#모든행에 대해서, 컬럼 0과 2만 얻기

In [21]:
#임의의 어레이 두 개 생성
x1=np.arange(0,12).reshape(4,3)
x2=np.arange(100,112).reshape(4,3)
x1,x2

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([[100, 101, 102],
        [103, 104, 105],
        [106, 107, 108],
        [109, 110, 111]]))

In [22]:
#디폴트는 행 방향(세로)으로 붙인다.
x3=np.concatente((x1,x2))
x3

AttributeError: ignored

In [23]:
#컬러망향으로 붙이기(axis=1)
x3=np.concatenate((x1,x2),axis=1)
x3

array([[  0,   1,   2, 100, 101, 102],
       [  3,   4,   5, 103, 104, 105],
       [  6,   7,   8, 106, 107, 108],
       [  9,  10,  11, 109, 110, 111]])

In [24]:
#어레이를 csv파일로 저장한 후 파일 읽기

In [25]:
#csv파일의 내용을 어레이로 바로 읽기